config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :recipes
  root to: 'recipes#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about' => 'recipes#about'


  get 'registration_recipe' => 'recipes#registration_recipe'
  get 'recipe/:id' => 'recipes#show_recipe', as: 'show_recipe'
  get 'recipe/:id/edit' => 'recipes#edit', as: 'edit_recipe'
  patch 'recipe/:id' => 'recipes#update', as: 'update_recipe'
  delete 'destroy/:id' => 'recipes#destroy', as: 'destroy_recipe'

  get 'user/:id' => 'users#show', as: 'show_user'
  get 'users/:id/edit' => 'users#edit', as: 'edit_user'
  patch 'users/:id' => 'users#update', as: 'update_user'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  
  validates :recipe_name, presence: true

  belongs_to :user
  attachment :cooking_image
  has_many :procedures, dependent: :destroy
  has_many :foods, dependent: :destroy

  accepts_nested_attributes_for :procedures, allow_destroy: true
  accepts_nested_attributes_for :foods, allow_destroy: true


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :authenticate_user!, {only: [:registration_recipe, :create, :edit, :update, :destroy]}

	# トップページ
	def show
		@recipes = Recipe.page(params[:page]).reverse_order # 新しいもの順
	end

	# このサイトについて
	def about
	end

	# レシピ投稿画面表示用コントローラ
	def registration_recipe
		@recipe = Recipe.new
		@recipe.foods.build
		@recipe.procedures.build
	end

	def create
		@recipe = Recipe.new(recipe_params) # ストロングパラメータから精査されたデータだけをインスタンスに格納
  		@recipe.user_id = current_user.id
		@procedures = @recipe.procedures.order('no')	# リダイレクト先での表示用
  		if @recipe.save
  			render action: :show_recipe
  		else
  			render action: :registration_recipe
  		end
	end


	def show_recipe
		@recipe = Recipe.find(params[:id])
		@procedures = @recipe.procedures.order('no')

	end

	def edit
		@user = current_user
		@recipe = Recipe.find(params[:id])
  	end

  	def update
  		@recipe = Recipe.find(params[:id])
		@procedures = @recipe.procedures.order('no')	# リダイレクト先での表示用
  		if @recipe.user_id == current_user.id
	  		if @recipe.update(recipe_params)
	  			render action: :show_recipe
	  		else
	  			render action: :edit
	  		end
	  	else # レシピを投稿したユーザーとログイン中のユーザーが不一致の場合、更新せずトップページに戻る
	  		redirect_to root_path
	  	end
  	end

	def destroy
        recipe = Recipe.find(params[:id])
        if recipe.user_id == current_user.id
        	recipe.destroy
        	redirect_to root_path # flash: {notice: 'レシピを削除しました。'}
        else
        	redirect_to show_recipe_path(recipe.id)
        end
    end


	Refile.secret_key = '3e025e06ffe36efaa0da3950a4cdfb2662cc56c3da1f1fb82bc6c2709976d433904d6dd2a13711f348c5f864f9c12f0e8cabdd116df3f530c0ee2d134a7868c7'
	private

	def recipe_params
		params.require(:recipe).permit(
			:recipe_name, :author_comment, :cooking_image,
			foods_attributes: [:id, :recipe_id, :food_name, :amount],
			procedures_attributes: [:id, :recipe_id, :no, :detail, :picture])
	end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/about.html.erb
<div class="container">
    <h1>ようこそ　WMRecipesへ！！</h1><br>
    <h2>概要</h2>
    <p>このサイトは、業務スーパーで購入できる食材をメインに使って作った料理のレシピを投稿するサイトです。</p>
    <p>できれば全て業務スーパーのみで購入した食材であることが望ましいですが、そのあたりの匙加減は使われる皆様におまかせします。</p>
    <p>ちなみにWMRecipesの名前の由来は「Wholesale Market」（業務スーパーの意訳）の頭文字にRecipeを足したものです。</p>

    <h2>こんな方にはぜひ使って欲しい</h2>
    <li>料理が好き！</li>
    <li>買い物は極力業務スーパーのみで済ませたいが、料理のレパートリーを増やしたい！</li>
    <li>業務スーパーで買った食材・商品の思いもよらぬ使い方を見つけてしまって共有したい！</li>
    <br>
    <p>余談ですが、サイトの製作者はパスタが得意ですが他のジャンルはからっきしです。皆様の知恵をレシピ投稿という形でお貸しいただけるととても喜びます。</p>


    <h2>注意点</h2>
    <p>Web開発の経験が浅い身の人間が作ったものであるため、ユーザー登録の際には特定されても問題のないメールアドレスを登録してください。</p>
    <p>パスワード忘れのメールが届かなくても問題ない方は適当なアドレスで結構です。</p>
</div>

app/views/recipes/edit.html.erb
<p class="notice"><%= flash.notice %></p>
<div class="container">
	<%= form_for(@recipe, url: update_recipe_path) do |r| %>
		<div class="clearfix">
			<div class="col-xs-5">
				<h2>料理画像</h2>
	        	<%= r.attachment_field :cooking_image %>

			</div>
			<div class="col-xs-7">
				<h2>レシピ名</h2>
				<%= r.text_field :recipe_name, style:"width:100%" %>
				<h2>投稿者コメント</h2>
				<%= r.text_area :author_comment, style:"width:100%" %>
			</div>
		</div>
		<div class="food">
			<h2 class="form">食材</h2>
			<table class="col-xs-12 table table-hover">
				<thead>
					<td class="col-xs-1"></td>
					<th class="col-xs-1"></th>
					<th class="col-xs-7">材料名</th>
					<th class="col-xs-2">量</th>
					<th class="col-xs-1"></th>
				</thead>
				<tbody>
					<%= r.nested_fields_for :foods, wrapper_tag: :tr do |f| %>
						<td></td>
						<td></td>
						<td><%= f.text_field :food_name, style:"width:100%" %></td>
						<td><%= f.text_field :amount, style:"width:100%", class: 'text-left'  %></td>
						<td><%= f.remove_nested_fields_link '削除', class: 'btn btn-danger', role: 'button' %></td>
					<% end %>
				</tbody>
			</table>
			<%= r.add_nested_fields_link :foods, '＋', class: 'btn add_btn', role: 'button' %>
			<!-- テーブルタグ使って並べる -->
		</div>

		<div class="procedure">
			<h2 class="form">手順</h2>
			<table class="col-xs-12 table table-hover">
				<thead>
					<th class="col-xs-1"></th>
					<th class="col-xs-1">番号</th>
					<th class="col-xs-7">内容</th>
					<th class="col-xs-2">添付画像</th>
					<th class="col-xs-1"></th>
				</thead>
				<%= r.nested_fields_for :procedures, wrapper_tag: :tbody do |p| %>
				<tr>
					<td></td>
					<td><%= p.text_field :no, style:"width:100%" %></td>
					<td><%= p.text_area :detail, style:"width:100%" %></td>
					<td><%= p.attachment_field :picture, class: 'picture_button' %></td>
					<td><%= p.remove_nested_fields_link '削除', class: 'btn-margin btn btn-danger', role: 'button' %></td>
				</tr>
				<% end %>
			</table>
			<%= r.add_nested_fields_link :procedures, '＋', class: 'btn add_btn', role: 'button' %>
		</div>

		<div class="submit col-xs-12">
			<%= r.submit '投稿', class: 'btn-margin btn btn-primary' %>
		</div>

	<% end %>
</div>

app/views/recipes/registration_recipe.html.erb
<p class="notice"><%= flash.notice %></p>
<div class="container">
	<div class="row">
	<%= form_for(@recipe, url: '/recipes') do |r| %>
		<div class="clearfix">
			<div class="col-xs-5">
				<h2>料理画像</h2>
	        	<%= r.attachment_field :cooking_image %>

			</div>
			<div class="col-xs-7">
				<h2>レシピ名</h2>
				<%= r.text_field :recipe_name, style:"width:100%" %>
				<h2>投稿者コメント</h2>
				<%= r.text_area :author_comment, style:"width:100%" %>
			</div>
		</div>
		<div class="food">
			<h2 class="form">食材</h2>
			<p>ここには業務スーパーで購入した商品名を入力してください（調味料は例外）</p>
			<table class="col-xs-12 table table-hover">
				<thead>
					<td class="col-xs-1"></td>
					<th class="col-xs-1"></th>
					<th class="col-xs-7">材料名</th>
					<th class="col-xs-2">量</th>
					<th class="col-xs-1"></th>
				</thead>
				<tbody>
					<%= r.nested_fields_for :foods, wrapper_tag: :tr do |f| %>
						<td></td>
						<td></td>
						<td><%= f.text_field :food_name, style:"width:100%" %></td>
						<td><%= f.text_field :amount, style:"width:100%", class: 'text-left'  %></td>
						<td><%= f.remove_nested_fields_link '削除', class: 'btn btn-danger', role: 'button' %></td>
					<% end %>
				</tbody>
			</table>
			<%= r.add_nested_fields_link :foods, '＋', class: 'btn add_btn', role: 'button' %>
			<!-- テーブルタグ使って並べる -->
		</div>

		<div class="procedure">
			<h2 class="form">手順</h2>
			<table class="col-xs-12 table table-hover">
				<thead>
					<th class="col-xs-1"></th>
					<th class="col-xs-1">番号</th>
					<th class="col-xs-7">内容</th>
					<th class="col-xs-2">添付画像</th>
					<th class="col-xs-1"></th>
				</thead>
				<%= r.nested_fields_for :procedures, wrapper_tag: :tbody do |p| %>
				<tr>
					<td></td>
					<td><%= p.text_field :no, style:"width:100%" %></td>
					<td><%= p.text_area :detail, style:"width:100%" %></td>
					<td><%= p.attachment_field :picture, class: 'picture_button' %></td>
					<td><%= p.remove_nested_fields_link '削除', class: 'btn-margin btn btn-danger', role: 'button' %></td>
				</tr>
				<% end %>
			</table>
			<%= r.add_nested_fields_link :procedures, '＋', class: 'btn add_btn', role: 'button' %>
		</div>

		<div class="submit col-xs-12">
			<%= r.submit '投稿', class: 'btn-margin btn btn-primary' %>
		</div>

	<% end %>
</div>
</div>

app/views/recipes/show.html.erb
<div class="disp">
	<div class="mask">
		<div class="container-fluid">

			<div class="col-sm-4">
			</div>
			<div class="buttons_parent col-sm-4">
				<div class="buttons">
					<% if user_signed_in? %>
						<%= link_to 'レシピ投稿', registration_recipe_path,  class: "btn btn-primary btn-block" %>
						<%= link_to 'ログアウト', destroy_user_session_path, :method => :delete,  class: "btn btn-primary btn-block" %>
					<% else %>
						<%= link_to 'ログイン', new_user_session_path,  class: "btn btn-primary btn-block" %>
						<%= link_to 'ユーザー登録', new_user_registration_path,  class: "btn btn-primary btn-block" %>
					<% end %>
				</div>
			</div>
			<div class="col-sm-4">
			</div>
		</div>
	</div>
</div>
<div class="recipes">
	<div class="container">
		<div class="row">
			<% if @recipes.present? %>
			<% @recipes.each do |recipe| %>
				<div class="recipe_block col-sm-4 col-xs-12">
					<%= attachment_image_tag recipe, :cooking_image, :fill, 250, 250, fallback: "noImage.png", size: "250x250" %><br>
					<%= link_to recipe.recipe_name, show_recipe_path(recipe.id) %>
				</div>
			<% end %>
		</div>
		<%= paginate @recipes, class: "pagenate" %>
		<% end %>
	</div>
</div>

app/views/recipes/show_recipe.html.erb
<div class="container">
	<div class="row recipe_info">
		<div class="col-xs-5">
			<%= attachment_image_tag @recipe, :cooking_image, :fill, 250, 250, fallback: "noImage.png", size: "250x250" %>
			<br>
			<section class="author_name">
				投稿者名：<%= link_to @recipe.user.user_name, show_user_path(@recipe.user_id)  %></section>
		</div>
		<div class="col-xs-7">
			<h2>レシピ名</h2>
			<%= @recipe.recipe_name %>
			<h2>投稿者コメント</h2>
			<%= @recipe.author_comment %>
		</div>
	</div>
	<div class="row">
		<div class="food">
			<h2 class="form">食材</h2>
			<table class="col-xs-12 table table-hover">
				<thead>
						<th class="col-xs-1"></th>
						<th class="col-xs-1"></th>
						<th class="col-xs-7">材料名</th>
						<th class="col-xs-2">量</th>
						<th class="col-xs-1"></th>
				</thead>
				<tbody>
					<% @recipe.foods.each do |f| %>
						<tr>
							<td class="col-xs-1"></td>
							<td class="col-xs-1"></td>
							<td class="col-xs-7 text-left"><%= f.food_name %></td>
							<td class="col-xs-2 text-left"><%= f.amount %></td>
							<td class="col-xs-1"></td>
						</tr>
					<% end %>
				</tbody>
		</table>
		</div>
	</div>
	<div class="row">
		<div class="procedure">
			<h2 class="form">手順</h2>
			<table class="col-xs-12 table table-hover">
				<thead>
						<th class="col-xs-1 bottom-line"></th>
						<th class="col-xs-1">番号</th>
						<th class="col-xs-7">内容</th>
						<th class="col-xs-2"></th>
						<th class="col-xs-1"></th>
				</thead>
				<tbody>
					<% @procedures.each do |p| %>
						<tr>
							<td></td>
							<td><%= p.no %></td>
							<td class="text-left procedure-text"><%= p.detail%></td>
							<td>
								<% if p.picture.present? %>
										<%= attachment_image_tag p, :picture, :fill, 200, 200, fallback: "no_image.jpg", size: "200x200" %>
								<% end %>
							</td>
							<td></td>
						</div>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
        <% if user_signed_in? %>
			<% if @recipe.user_id == current_user.id %>
				<div class="col-xs-12 submit">
					<%= link_to '編集', edit_recipe_path(@recipe.id), class: 'btn-margin btn btn-success btn-sm' %>
					<%= link_to '削除', destroy_recipe_path(@recipe.id), method: :delete, class: 'btn-margin btn btn-danger btn-sm' %>
				</div>
			<% end %>
		<% end %>
	</div>
</div>