config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :recipes
  root to: 'recipes#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about' => 'recipes#about'


  get 'registration_recipe' => 'recipes#registration_recipe'
  get 'recipe/:id' => 'recipes#show_recipe', as: 'show_recipe'
  get 'recipe/:id/edit' => 'recipes#edit', as: 'edit_recipe'
  patch 'recipe/:id' => 'recipes#update', as: 'update_recipe'
  delete 'destroy/:id' => 'recipes#destroy', as: 'destroy_recipe'

  get 'user/:id' => 'users#show', as: 'show_user'
  get 'users/:id/edit' => 'users#edit', as: 'edit_user'
  patch 'users/:id' => 'users#update', as: 'update_user'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WMRecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <!-- 非ログイン時 -->
    <div class="container">
      <div class ="row">
        <nav class="navbar">
          <ul class="nav navbar-nav navbar-header">
            <li>
              <%= link_to 'WMRecipes', root_path, class: "header-text" %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to 'このサイトについて', about_path %></li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= attachment_image_tag current_user, :icon, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40" %>
                  <%= current_user.user_name %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'レシピ投稿', registration_recipe_path %></li>
                  <li><%= link_to 'ユーザ設定', edit_user_path(current_user.id) %></li>
                  <li><%= link_to 'ログアウト', destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'このサイトについて', about_path %></li>
              <li><%= link_to 'ログイン', new_user_session_path %></li>
              <li><%= link_to 'ユーザー登録', new_user_registration_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>

  <footer>
    <span class="frame-text">
      © 2019 taka_prog
    </span>
  </footer>
</html>